# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NNMemoryGame' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NNMemoryGame

	pod 'Mantle', '~> 2.0'
	pod 'SwiftyJSON'
	pod 'TPKeyboardAvoiding', '~> 1.3'
	pod 'ActionSheetPicker-3.0'
	pod 'MBProgressHUD', '~> 1.1'
	pod 'Alamofire', '~> 4.5'
	pod 'PINCache', '3.0.1-beta.6'
	pod 'SwiftyJSON', '~> 4.0'
	pod 'Alamofire-SwiftyJSON'
	
end
